// Restricted to the existing synthetic QA application. Never accept a production URL.
const {chromium,devices}=require('C:/Users/roddr/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('fs'),path=require('path'),crypto=require('crypto'),assert=require('assert/strict');
const root=path.resolve(__dirname,'..'),base='http://127.0.0.1:19103/SGC',out=path.join(__dirname,'results/beta-adicional-20261006');fs.mkdirSync(out,{recursive:true});
const people=JSON.parse(fs.readFileSync(path.join(root,'.secrets/qa_preentrega_finalcredentials.json'))),saved=JSON.parse(fs.readFileSync(path.join(root,'.secrets/qa_preentrega_finalsessions.json')));
assert.deepEqual(people.map(x=>x.login).sort(),['iceman','maverick','viper']);
const mode=process.argv[2]||'load',report={mode,startedAt:new Date().toISOString(),checks:[],requests:[],errors:[]},contexts=[];
function code(key){let b=0,v=0,a=[];for(const c of key){v=(v<<5)|'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567'.indexOf(c);b+=5;if(b>=8){b-=8;a.push((v>>b)&255)}}const n=Buffer.alloc(8);n.writeBigUInt64BE(BigInt(Math.floor(Date.now()/30000)));const d=crypto.createHmac('sha1',Buffer.from(a)).update(n).digest(),i=d[19]&15;return String((d.readUInt32BE(i)&0x7fffffff)%1000000).padStart(6,'0')}
async function account(browser,login,options={}){
 const c=await browser.newContext({...options,storageState:saved[login].state});contexts.push(c);const p=await c.newPage();p.setDefaultTimeout(20000);p.on('pageerror',e=>report.errors.push({kind:'javascript',name:e.name}));await p.goto(base+'/');
 await p.waitForFunction(()=>document.querySelector('#logout')||document.querySelector('#login-form')||document.querySelector('#user-mfa-form'));
 if(await p.locator('#login-form').count()){const person=people.find(x=>x.login===login);await p.fill('#login-form [name=login]',login);await p.fill('#login-form [name=password]',person.password);await p.click('#login-form button');await p.locator('#user-mfa-form').waitFor()}
 if(await p.locator('#user-mfa-form').count()){if(saved[login].lastMfaCounter>=Math.floor(Date.now()/30000))await p.waitForTimeout(30100-Date.now()%30000);await p.locator('#user-mfa-form button:enabled').waitFor();const r=p.waitForResponse(r=>r.url().endsWith('/api/auth/mfa/verify'));await p.fill('#user-mfa-form [name=code]',code(saved[login].key));await p.click('#user-mfa-form button');assert.equal((await r).status(),200);saved[login].lastMfaCounter=Math.floor(Date.now()/30000)}
 await p.locator('#logout').waitFor({state:'attached'});await p.waitForFunction(()=>typeof state!=='undefined'&&state.records);saved[login].state=await c.storageState();return p;
}
async function request(p,method,url,data){const csrf=await p.evaluate(()=>csrfToken);assert(csrf,'CSRF cookie missing');const t=Date.now();const r=await p.request.fetch(base+url,{method,data,headers:{'X-CSRF-Token':csrf}});report.requests.push({method,path:url.replace(/[a-f0-9-]{36}/g,'ID'),status:r.status(),ms:Date.now()-t});return r}
async function checkpoint(name,fn){await fn();report.checks.push({name,passed:true});console.log('PASS '+name)}
(async()=>{let browser;try{
 browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
 if(mode==='load'){
 const pages=[];for(const login of ['maverick','iceman','viper'])pages.push(await account(browser,login));
 const h=await pages[0].request.get(base+'/api/health');assert.equal((await h.json()).schema,11);
 const docs=Array.from({length:12},(_,i)=>({id:crypto.randomUUID(),title:'Carga QA '+i,text:'<p>Somente teste sintético de concorrência.</p>',category:'Manutenção',local:'QA',date:'2026-10-06',who:'QA',progress:'Em andamento',photos:[],status:'draft',revision:1}));
 await checkpoint('12 records created concurrently by three accounts',async()=>{await Promise.all(docs.map(async(d,i)=>{const r=await request(pages[i%3],'POST','/api/records',{document:d,condominiumId:'sqa'});assert.equal(r.status(),201);docs[i]=(await r.json()).document}))});
 await checkpoint('12 independent concurrent edits persist revision 2',async()=>{await Promise.all(docs.map(async(d,i)=>{const r=await request(pages[i%3],'PATCH','/api/records/'+d.id,{document:{...d,local:'QA edited '+i},expectedRevision:1});assert.equal(r.status(),200);docs[i]=(await r.json()).document;assert.equal(docs[i].revision,2)}))});
 await checkpoint('five competing edits produce one winner and four conflicts',async()=>{const responses=await Promise.all(Array.from({length:5},(_,i)=>request(pages[0],'PATCH','/api/records/'+docs[0].id,{document:{...docs[0],local:'QA conflict '+i},expectedRevision:2})));assert.deepEqual(responses.map(r=>r.status()).sort(),[200,409,409,409,409]);docs[0]=(await responses.find(r=>r.status()===200).json()).document;assert.equal(docs[0].revision,3)});
 await checkpoint('six concurrent synthetic photo saves and verified downloads',async()=>{await Promise.all(docs.slice(0,6).map(async(d,i)=>{const src=await pages[i%3].evaluate(i=>{const c=document.createElement('canvas');c.width=320;c.height=200;const x=c.getContext('2d');x.fillStyle='#245789';x.fillRect(0,0,320,200);x.fillStyle='white';x.fillText('QA '+i,20,30);return c.toDataURL('image/png')},i);const r=await request(pages[i%3],'PATCH','/api/records/'+d.id,{document:{...d,photos:[{src,caption:'Synthetic QA',phase:'Antes'}]},expectedRevision:d.revision});assert.equal(r.status(),200);docs[i]=(await r.json()).document;const m=await pages[i%3].request.get(new URL(docs[i].photos[0].src,base+'/').href);assert.equal(m.status(),200);assert((await m.body()).length>0)}))});
 let editions=[];
 await checkpoint('three independent edition creates and parallel edits',async()=>{await Promise.all(pages.map(async(p,i)=>{const d={id:crypto.randomUUID(),title:'Informe carga QA '+i,period:'Outubro de 2026',blocks:[],status:'draft',version:1};const r=await request(p,'POST','/api/editions',{document:d,condominiumId:'sqa'});assert.equal(r.status(),201);const doc=(await r.json()).document;const edit=await request(p,'PATCH','/api/editions/'+doc.id,{document:{...doc,title:doc.title+' revisado'},expectedRevision:1});assert.equal(edit.status(),200);editions[i]=(await edit.json()).document}))});
 await checkpoint('60 workspace reads at six simultaneous requests',async()=>{for(let n=0;n<10;n++)await Promise.all(Array.from({length:6},async(_,i)=>{const r=await request(pages[i%3],'GET','/api/workspace');assert.equal(r.status(),200)}))});
 await checkpoint('records retain own revisions and production fixture remains intact',async()=>{for(let i=0;i<pages.length;i++){const ws=await (await pages[i].request.get(base+'/api/workspace')).json();for(let j=i;j<docs.length;j+=3){const actual=ws.state.records.find(r=>r.id===docs[j].id);assert(actual);assert.equal(actual.revision,docs[j].revision);assert.equal(actual.local,docs[j].local)}}});
 fs.writeFileSync(path.join(out,'load-ids.json'),JSON.stringify({records:docs.map(d=>d.id),editions:editions.map(d=>d.id)},null,2));
 }else if(mode==='compatibility'){
 const profiles=[['Chrome desktop',{viewport:{width:1365,height:950}}],['Android emulation',{...devices['Pixel 5']}],['iPhone emulation',{...devices['iPhone 13']}]];
 for(const [label,options] of profiles){const p=await account(browser,'maverick',options);await checkpoint(label+' navigation and form',async()=>{for(const route of ['inicio','registros','informes','novo']){await p.goto(base+'/#'+route);await p.locator('#main h1').first().waitFor();await p.waitForFunction(route=>document.querySelector('#main')?.dataset.route==='#'+route,route);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Horizontal overflow '+label+' '+route)}await p.waitForFunction(()=>typeof tinymce!=='undefined'&&tinymce.get('record-text')?.initialized);await p.fill('[name=title]','Compatibilidade QA');await p.fill('[name=local]','QA');await p.evaluate(()=>{const e=tinymce.get('record-text');e.setContent('<p>Teste de formulário e teclado.</p>');e.fire('change')});await p.click('button[value=draft]');await p.waitForURL(/#registro\//);const id=new URL(p.url()).hash.split('/')[1];await p.reload();await p.locator('#main h1').first().waitFor();assert((await p.locator('#main').textContent()).includes('Compatibilidade QA'));report.checks[report.checks.length]?.id;await p.screenshot({path:path.join(out,label.replaceAll(' ','-')+'.png'),fullPage:false})});await p.context().close()}
 await browser.close();browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});const p=await account(browser,'maverick',{viewport:{width:1365,height:950}});await checkpoint('Edge desktop authenticated navigation',async()=>{await p.goto(base+'/#informes');await p.locator('#main h1').first().waitFor();assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await p.screenshot({path:path.join(out,'Edge-desktop.png'),fullPage:false})});
 report.limits=['Mobile devices are emulated in Chromium; native Android, iOS and Safari still require user-device validation.'];
 }else throw Error('Unsupported mode');
 assert.deepEqual(report.errors,[]);report.passed=true;
 }catch(e){report.passed=false;report.errors.push({kind:'assertion',name:e.name,message:String(e.message).replace(/(password|token|cookie|key)\S*/gi,'[private]').slice(0,180)});process.exitCode=1;
 }finally{for(const c of contexts){try{await c.close()}catch{}}if(browser)await browser.close();fs.writeFileSync(path.join(root,'.secrets/qa_preentrega_finalsessions.json'),JSON.stringify(saved));report.finishedAt=new Date().toISOString();const timings=report.requests.map(r=>r.ms).sort((a,b)=>a-b);report.performance={requests:timings.length,p95Ms:timings[Math.ceil(timings.length*.95)-1]||0,maxMs:timings.at(-1)||0};fs.writeFileSync(path.join(out,mode+'.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({passed:report.passed,checks:report.checks.length,performance:report.performance,errors:report.errors}))}
})();
