const {chromium}=require('C:/Users/roddr/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),crypto=require('node:crypto'),assert=require('node:assert/strict'),path=require('node:path');
const root=path.resolve(__dirname,'..'),base='http://127.0.0.1:19101/SGC';
const password=fs.readFileSync(path.join(root,'.secrets/qa_owner_password'),'utf8').trim(),token=fs.readFileSync(path.join(root,'.secrets/qa_beta_invitation'),'utf8').trim();
function code(key){let bits=0,value=0,bytes=[];for(const c of key){value=(value<<5)|'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567'.indexOf(c);bits+=5;if(bits>=8){bits-=8;bytes.push((value>>bits)&255);}}const counter=Buffer.alloc(8);counter.writeBigUInt64BE(BigInt(Math.floor(Date.now()/30000)));const digest=crypto.createHmac('sha1',Buffer.from(bytes)).update(counter).digest(),offset=digest[19]&15;return String((digest.readUInt32BE(offset)&0x7fffffff)%1000000).padStart(6,'0');}
(async()=>{const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
try{const ctx=await browser.newContext({viewport:{width:390,height:844}}),page=await ctx.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.name));await page.goto(base+'/');
await page.locator('#activate-form').locator('..').locator('summary').click();
await page.fill('#activate-form [name=login]','andre');await page.fill('#activate-form [name=token]',token);await page.fill('#activate-form [name=password]',password);await page.click('#activate-form button');
await page.locator('#user-mfa-form').waitFor();const qr=page.locator('.auth-qr');await qr.waitFor();assert(await qr.evaluate(img=>img.complete&&img.naturalWidth>200));
assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));const key=await page.locator('#user-mfa-setup code').textContent();await page.setViewportSize({width:1365,height:900});
await page.fill('#user-mfa-form [name=code]',code(key));await page.click('#user-mfa-form button');await page.locator('#logout').waitFor();assert.equal(await page.locator('.auth-qr').count(),0);
await page.click('#logout');await page.locator('#login-form').waitFor();await page.fill('#login-form [name=login]','andre');await page.fill('#login-form [name=password]',password);await page.click('#login-form button');await page.locator('#user-mfa-form').waitFor();assert.equal(await page.locator('.auth-qr').count(),0);await page.click('#mfa-cancel');
await page.locator('#recovery-form').locator('..').locator('summary').click();await page.fill('#recovery-form [name=login]','andre');await page.selectOption('#recovery-form [name=kind]','authenticator');await page.click('#recovery-form button');await page.getByText('Se a conta puder ser recuperada, o responsável entregará as instruções.').waitFor();
const ownerPage=await (await browser.newContext({viewport:{width:1365,height:900}})).newPage();ownerPage.on('pageerror',e=>errors.push(e.name));await ownerPage.goto(base+'/owner.html');await ownerPage.fill('#login-form [name=login]','rodrigo');await ownerPage.fill('#login-form [name=password]',password);await ownerPage.click('#login-form button');await ownerPage.locator('#owner-unlock').waitFor();await ownerPage.fill('#owner-unlock [name=password]',password);await ownerPage.click('#owner-setup');await ownerPage.locator('#setup-area:not([hidden])').waitFor();const ownerKey=await ownerPage.locator('#setup-key').textContent();await ownerPage.fill('#owner-unlock [name=code]',code(ownerKey));await ownerPage.click('#owner-unlock [type=submit]');await ownerPage.locator('.recovery-item').waitFor();const form=ownerPage.locator('.recovery-item').filter({hasText:'andre'});await form.locator('[name=reason]').fill('Identidade confirmada por telefone conhecido');await form.locator('[name=identityConfirmed]').check();await form.locator('[name=resetAuthenticator]').check();await form.locator('[value=issue]').click();await form.locator('.token-result').filter({hasText:'Entregue pessoalmente'}).waitFor();
assert.deepEqual(errors,[]);console.log('PASS: mobile activation to QR/MFA, MFA-required re-login, cancel, public recovery request and exclusive owner queue/token issuance; no JS errors');
await ownerPage.locator('[data-owner-space="sqa"]').click();await ownerPage.locator('.owner-space-note').waitFor();assert((await ownerPage.locator('.owner-space-note').textContent()).includes('Trocar espaço'));
await ownerPage.getByRole('link',{name:'Trocar espaço / painel do dono'}).click();await ownerPage.locator('[data-owner-space="sqa"]').waitFor();await ownerPage.locator('#owner-lock').click();await ownerPage.locator('#owner-unlock').waitFor();await ownerPage.goto(base+'/');await ownerPage.waitForURL('**/owner.html');await ownerPage.locator('#owner-unlock').waitFor();assert.deepEqual(errors,[]);console.log('PASS: exclusive owner space entry, named workspace banner, return to panel and mandatory re-unlock after lock');
}finally{await browser.close();}})().catch(error=>{console.error(error.name+': '+error.message.replaceAll(password,'[redacted]').replaceAll(token,'[redacted]'));process.exitCode=1;});
