const {chromium}=require(process.env.PLAYWRIGHT_MODULE);
const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
const base=process.env.QA_URL;assert(base&&new URL(base).port==='19001');
const out=process.env.QA_RESULTS_DIR||path.join(__dirname,'results','intensive');fs.mkdirSync(out,{recursive:true});
(async()=>{
 const browser=await chromium.launch({executablePath:'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe',headless:true});
 const context=await browser.newContext({viewport:{width:1440,height:1050},acceptDownloads:true});
 let page=await context.newPage();page.setDefaultTimeout(7000);const checks=[],inventory=[];
 const cleanDraft=async()=>page.evaluate(async()=>{try{if(typeof clearActiveDraft==='function')await clearActiveDraft();}catch{}try{if(typeof closeDraftDialog==='function')closeDraftDialog();}catch{}const recovery=document.querySelector('#storage-recovery');if(recovery)recovery.remove();if(typeof storageBlocked!=='undefined')storageBlocked=false;if(typeof pendingOperation!=='undefined')pendingOperation=null;}).catch(()=>{});
 const check=async(name,fn)=>{try{await fn();checks.push({name,passed:true});}catch(e){checks.push({name,passed:false,error:e.message.slice(0,1800)});await page.screenshot({path:path.join(out,'failure-'+checks.length+'.png'),fullPage:true}).catch(()=>{});}finally{await cleanDraft();}console.log((checks.at(-1).passed?'PASS ':'FAIL ')+name);};
 const goto=async(route)=>{await page.goto(base+'/#'+route);await page.waitForFunction(()=>state?.editions);};
 const ready=()=>page.waitForFunction(()=>tinymce.get('record-text')?.initialized);
 const seed=async()=>{await goto('inicio');await page.evaluate(async()=>{const pubs=state.publications;state=window.eval('seed()');state.publications=pubs;await persist();});};
 try{
  await seed();
  for(const route of ['inicio','registros','revisao','novo','nota','registro/r1','complemento/r1','informes','selecionar/e1','editor/e1','previa/e1','lixeira']){
   await goto(route);
   inventory.push({route,fields:await page.locator('#main input,#main select,#main textarea').evaluateAll(nodes=>nodes.map(n=>({tag:n.tagName,id:n.id,name:n.name,type:n.type,maxLength:n.maxLength,options:n.options?[...n.options].map(o=>o.value):undefined})))});
  }
  await check('Registro: assunto 160 caracteres e truncamento em 161',async()=>{await goto('novo');await page.fill('[name=title]','x'.repeat(161));assert.equal((await page.inputValue('[name=title]')).length,160);});
  await check('Registro: revisão bloqueia texto/assunto vazios',async()=>{await goto('novo');await ready();await page.click('button[value=review]');await page.getByText('Preencha o assunto e conte o que aconteceu antes de enviar.',{exact:true}).waitFor();assert(page.url().endsWith('#novo'));});
  await check('Registro: todos os campos persistem e escapam caracteres especiais',async()=>{
   await goto('novo');await ready();await page.fill('[name=title]','QA aspas " <img src=x onerror=alert(1)> São João 😀');
   await page.fill('[name=local]','Garagem & salão <teste>');await page.fill('[name=who]','José d’Ávila');await page.fill('[name=date]','2024-02-29');await page.selectOption('[name=category]','Outro');await page.selectOption('[name=progress]','Em andamento');
   await page.evaluate(()=>tinymce.get('record-text').setContent('<p><strong>Informação</strong> com acentos e emoji 😀.</p>'));
   await page.click('button[value=review]');await page.waitForURL(/#registro\//);await page.reload();await page.locator('.detail-text').waitFor({state:'attached'});
   const r=await page.evaluate(()=>state.records.find(r=>r.id===location.hash.split('/')[1]));assert.equal(r.local,'Garagem & salão <teste>');assert.equal(r.who,'José d’Ávila');assert.equal(r.date,'2024-02-29');assert.equal(r.category,'Outro');assert.equal(r.progress,'Em andamento');assert.equal(await page.locator('.page-head img').count(),0);
  });
  for(const value of ['Obra','Compra','Manutenção','Reparo','Serviço','Evento','Nota solta','Outro'])await check('Categoria: '+value,async()=>{
   await goto('novo');await ready();await page.fill('[name=title]','Categoria QA '+value);await page.selectOption('[name=category]',value);await page.click('button[value=draft]');await page.waitForURL(/#registro\//);await page.reload();await page.locator('.detail-text').waitFor({state:'attached'});assert.equal(await page.evaluate(()=>state.records.find(r=>r.id===location.hash.split('/')[1]).category),value);
  });
  for(const value of ['Não informado','Em andamento','Concluído'])await check('Andamento: '+value,async()=>{await goto('novo');await ready();await page.selectOption('[name=progress]',value);await page.click('button[value=draft]');await page.waitForURL(/#registro\//);assert.equal(await page.evaluate(()=>state.records.find(r=>r.id===location.hash.split('/')[1]).progress),value);});
  await check('Busca e filtros: todas as situações e categorias',async()=>{
   await goto('registros');for(const value of ['draft','review','ready','fix']){await page.selectOption('#filter-status',value);const states=await page.locator('#record-grid .badge').evaluateAll(ns=>ns.map(n=>n.className));assert(states.every(s=>s.includes(value)));}
   await page.selectOption('#filter-status','');for(const value of ['Obra','Compra','Manutenção','Reparo','Serviço','Evento','Nota solta','Outro']){await page.selectOption('#filter-category',value);assert(await page.evaluate(v=>[...document.querySelectorAll('#record-grid a')].every(a=>state.records.find(r=>a.hash==='#registro/'+r.id).category===v),value));}
   await page.fill('#search','inexistente-qa');assert.equal(await page.locator('.record-card').count(),0);
  });
  await check('Fotos: rejeitar tipo inválido, arquivo corrompido e acima de 12 MB',async()=>{
   await goto('novo');for(const f of [{name:'x.txt',mimeType:'text/plain',buffer:Buffer.from('x')},{name:'x.png',mimeType:'image/png',buffer:Buffer.from('not a photo')},{name:'large.jpg',mimeType:'image/jpeg',buffer:Buffer.alloc(12*1024*1024+1)}]){await page.setInputFiles('#photos-input',f);await page.waitForFunction(()=>!document.querySelector('#photos-input').disabled);assert.equal(await page.evaluate(()=>workingPhotos.length),0);}
  });
  await check('Fotos: quatro etapas, legenda especial e remoção',async()=>{
   await goto('novo');await page.setInputFiles('#photos-input',path.join(__dirname,'../public/images/jardim.jpg'));await page.waitForFunction(()=>workingPhotos.length===1&&!document.querySelector('#photos-input').disabled);
   for(const phase of ['Antes','Durante','Depois','Registro geral']){await page.selectOption('[data-phase]',phase);assert.equal(await page.evaluate(()=>workingPhotos[0].phase),phase);}
   await page.fill('[data-caption]','Antes & depois <teste> 😀');assert.equal(await page.evaluate(()=>workingPhotos[0].caption),'Antes & depois <teste> 😀');await page.click('[data-remove-photo]');assert.equal(await page.evaluate(()=>workingPhotos.length),0);
  });
  await check('Complemento: texto vazio bloqueado',async()=>{await goto('complemento/r1');await page.waitForFunction(()=>tinymce.get('feedback')?.initialized);await page.evaluate(()=>tinymce.get('feedback').setContent('<p> </p>'));await page.click('#save-feedback');assert(page.url().includes('#complemento/'));});
  await check('Novo informe: título e período vazios bloqueados',async()=>{await goto('informes');await page.click('#new-edition');await page.fill('#edition-title',' ');await page.fill('#edition-period',' ');await page.click('#create-edition');assert(await page.locator('#dialog').isVisible());await page.locator('#dialog .close').click();});
  await check('Informe: título, período, seção e corpo persistidos',async()=>{await goto('editor/e1');await page.waitForFunction(()=>editor?.instance?.initialized);await page.fill('#title-edition','Informe QA & teste');await page.fill('#period-edition','Setembro de 2026');await page.fill('#block-type','Seção QA');await page.fill('#block-title','Título QA');await page.evaluate(()=>editor.value='<p>Texto QA <em>formatado</em></p>');await page.click('#save-editor');await page.waitForFunction(()=>document.querySelector('#toast').textContent==='Edição salva no PostgreSQL.');await page.reload();await page.waitForFunction(()=>editor?.instance?.initialized);assert.equal(await page.inputValue('#block-title'),'Título QA');assert.equal(await page.inputValue('#title-edition'),'Informe QA & teste');assert.equal(await page.inputValue('#period-edition'),'Setembro de 2026');assert.equal(await page.inputValue('#block-type'),'Seção QA');assert(await page.evaluate(()=>editor.value.includes('<em>')));});
  await check('Informe: duplicar, reordenar, remover e desfazer bloco',async()=>{await goto('editor/e1');await page.waitForFunction(()=>editor?.instance?.initialized);await page.click('#duplicate-block');await page.waitForFunction(()=>state.editions.find(e=>e.id==='e1').blocks.length===2&&document.querySelectorAll('[data-block]').length===2);await page.click('#move-up');await page.waitForFunction(()=>document.querySelector('#move-up').disabled);await page.click('#move-down');await page.waitForFunction(()=>document.querySelector('#move-down').disabled);await page.click('#delete-block');await page.waitForFunction(()=>document.querySelectorAll('[data-block]').length===1);await page.click('#undo-block');await page.waitForFunction(()=>document.querySelectorAll('[data-block]').length===2);});
  await check('Bloco personalizado: nome só com espaços bloqueado',async()=>{await goto('editor/e1');await page.waitForFunction(()=>editor?.instance?.initialized);await page.click('#add-block');await page.fill('#custom-block-name','   ');await page.click('#custom-block-form button');assert(await page.locator('#dialog').isVisible());await page.locator('#dialog .close').click();});
  await check('Informe: alteração de legenda, orientação, comparação, capa e ocultação',async()=>{
   await goto('editor/e1');await page.evaluate(async()=>{activeBlock=0;state.editions.find(e=>e.id==='e1').blocks[0].photos=structuredClone(state.records.find(r=>r.id==='r1').photos);await persist();render();});await page.waitForFunction(()=>editor?.instance?.initialized);
   await page.fill('[data-edit-caption]','Legenda QA & acentos');await page.selectOption('#photo-layout','compare');
   for(const orientation of ['landscape','portrait','auto']){await page.selectOption('[data-orientation]',orientation);await page.waitForFunction(()=>editor?.instance?.initialized);}
   await page.click('[data-cover]');await page.click('[data-hide]');await page.waitForFunction(()=>document.querySelector('[data-hide]').textContent.includes('Mostrar'));await page.click('#go-preview');await page.waitForURL(/#previa/);assert.equal(await page.locator('.public-photos img').count(),0);
  });
  await check('Finalização exige confirmação explícita',async()=>{await goto('previa/e1');await page.click('#finalize');const n=await page.evaluate(()=>state.publications.length);await page.click('#confirm-publish');assert.equal(await page.evaluate(()=>state.publications.length),n);await page.locator('#dialog .close').click();});
  await check('Navegação protege e recupera rascunho não salvo',async()=>{await goto('novo');await ready();await page.fill('[name=title]','Rascunho importante não salvo');await page.click('nav a[href="#registros"]');await page.locator('#draft-navigation').waitFor();assert.equal(await page.inputValue('[name=title]'),'Rascunho importante não salvo');await page.click('#draft-stay');await page.click('nav a[href="#registros"]');await page.click('#draft-save');await page.waitForURL(/#registros$/);const saved=await (await page.request.get(base+'/api/state')).json();assert(saved.state.records.some(r=>r.title==='Rascunho importante não salvo'));await goto('novo');await ready();await page.fill('[name=title]','Rascunho recuperado após recarga');await page.reload();await page.waitForFunction(()=>document.querySelector('[name=title]')?.value==='Rascunho recuperado após recarga');});
  await check('Último bloco removido ainda permite desfazer',async()=>{await goto('editor/e1');await page.evaluate(async()=>{const e=state.editions.find(e=>e.id==='e1');e.blocks=e.blocks.slice(0,1);activeBlock=0;await persist();render();});await page.waitForFunction(()=>editor?.instance?.initialized);await page.click('#delete-block');await page.waitForFunction(()=>document.querySelectorAll('[data-block]').length===0);assert(await page.locator('#undo-block').isVisible());});
  await check('Edição recusa título e período só com espaços',async()=>{await seed();await goto('editor/e1');await page.waitForFunction(()=>editor?.instance?.initialized);await page.fill('#title-edition','   ');await page.fill('#period-edition','   ');await page.click('#save-editor');await page.waitForTimeout(300);const d=await page.request.get(base+'/api/state');const e=(await d.json()).state.editions.find(e=>e.id==='e1');assert(e.title.trim()&&e.period.trim());});
  await check('Informe inexistente não abre outro informe para edição',async()=>{await goto('editor/id-inexistente-qa');assert.equal(await page.locator('#title-edition').count(),0);});
  await check('Falha de rede: rascunho JSON e repetição recuperam salvamento',async()=>{await seed();await goto('novo');await ready();await page.fill('[name=title]','Falha de rede QA');await page.route('**/api/state',route=>route.request().method()==='PUT'?route.abort():route.continue());await page.click('button[value=draft]');await page.locator('#storage-recovery').waitFor();const dl=page.waitForEvent('download');await page.click('#download-draft');const download=await dl;const file=await download.path();const saved=JSON.parse(fs.readFileSync(file,'utf8'));assert.equal(saved.fields.title,'Falha de rede QA');await page.unroute('**/api/state');await page.click('#retry-draft');await page.locator('#storage-recovery').waitFor({state:'detached'});});
  for(const width of [320,390,768,1440])await check('Layout: largura '+width,async()=>{await page.setViewportSize({width,height:1000});for(const route of ['registros','novo','editor/e1','previa/e1']){await goto(route);await page.waitForTimeout(120);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),route);}});
 }finally{
  fs.writeFileSync(path.join(out,'fields.json'),JSON.stringify({at:new Date().toISOString(),checks,inventory},null,2));
  await browser.close();
 }
 console.log(JSON.stringify({passed:checks.filter(c=>c.passed).length,total:checks.length,failures:checks.filter(c=>!c.passed).map(c=>c.name)}));
 process.exitCode=checks.every(c=>c.passed)?0:1;
})().catch(e=>{console.error(e);process.exitCode=1;});
