const {chromium}=require('C:/Users/roddr/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),base=process.env.QA_BASE||'http://127.0.0.1:19102/SGC',phase=Number(process.env.QA_PHASE||1),out=process.env.QA_RESULTS||path.join(__dirname,'results','maverick');fs.mkdirSync(out,{recursive:true});
assert(/^http:\/\/127\.0\.0\.1:(19102|19103)\/SGC$/.test(base),'QA_BASE precisa ser destino local QA permitido');
const people=JSON.parse(fs.readFileSync(process.env.QA_CREDENTIALS||path.join(root,'.secrets/qa_maverick_credentials.json'))),privateFile=process.env.QA_SESSIONS||path.join(root,'.secrets/qa_maverick_sessions.json');
assert.deepEqual(people.map(p=>p.login).sort(),['iceman','maverick','viper'],'Somente contas sintéticas permitidas');
let saved=fs.existsSync(privateFile)?JSON.parse(fs.readFileSync(privateFile)):{};
const metaFile=path.join(out,'ids.json'),meta=fs.existsSync(metaFile)?JSON.parse(fs.readFileSync(metaFile)):{};
const checks=[],jsErrors=[],httpErrors=[];let current='startup',stepIndex=0;const skipCount=Number(process.env.QA_SKIP||0);
function code(key){let b=0,v=0,a=[];for(const c of key){v=(v<<5)|'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567'.indexOf(c);b+=5;if(b>=8){b-=8;a.push((v>>b)&255);}}const n=Buffer.alloc(8);n.writeBigUInt64BE(BigInt(Math.floor(Date.now()/30000)));const d=crypto.createHmac('sha1',Buffer.from(a)).update(n).digest(),i=d[19]&15;return String((d.readUInt32BE(i)&0x7fffffff)%1000000).padStart(6,'0');}
function redact(s){for(const p of people){s=s.replaceAll(p.token,'[token]').replaceAll(p.password,'[password]');}for(const p of Object.values(saved))if(p.key)s=s.replaceAll(p.key,'[mfa]');return s;}
(async()=>{const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});const contexts={};let page;
async function step(name,fn){current=name;if(++stepIndex<=skipCount&&stepIndex>1){checks.push({name,skipped:true});return;}try{await fn();checks.push({name,passed:true});console.log('PASS '+name);}catch(e){checks.push({name,passed:false,error:redact(e.message)});throw e;}}
async function finishMfa(p,login){const person=saved[login];assert(person?.key,'Chave MFA de QA ausente');if(person.lastMfaCounter>=Math.floor(Date.now()/30000))await p.waitForTimeout(30100-Date.now()%30000);await p.locator('#user-mfa-form button:enabled').waitFor();const counter=Math.floor(Date.now()/30000);const verified=p.waitForResponse(r=>r.url().endsWith('/api/auth/mfa/verify'));await p.fill('#user-mfa-form [name=code]',code(person.key));await p.click('#user-mfa-form button');assert.equal((await verified).status(),200,'MFA precisa ser confirmado pelo servidor');person.lastMfaCounter=counter;await p.locator('#logout').waitFor();}
async function account(login){const person=people.find(p=>p.login===login),context=await browser.newContext({viewport:{width:1365,height:950},acceptDownloads:true,...(saved[login]?.state?{storageState:saved[login].state}:{})});contexts[login]=context;const p=await context.newPage();p.setDefaultTimeout(12000);p.on('pageerror',e=>jsErrors.push({step:current,error:e.name+': '+redact(e.message)}));p.on('response',r=>{if(r.status()>=400&&r.url().includes('/api/'))httpErrors.push({step:current,path:new URL(r.url()).pathname,status:r.status()});});await p.goto(base+'/');
await p.waitForFunction(()=>document.querySelector('#logout')||document.querySelector('#login-form')||document.querySelector('#user-mfa-form'));
if(await p.locator('#login-form').count()){
 if(!saved[login]?.key){await p.locator('#activate-form').locator('..').locator('summary').click();await p.fill('#activate-form [name=login]',login);await p.fill('#activate-form [name=token]',person.token);await p.fill('#activate-form [name=password]',person.password);await p.click('#activate-form button');await p.locator('#user-mfa-form').waitFor();const key=await p.locator('#user-mfa-setup code').textContent();saved[login]={key};assert(await p.locator('.auth-qr').evaluate(i=>i.complete&&i.naturalWidth>200));}
 else {await p.fill('#login-form [name=login]',login);await p.fill('#login-form [name=password]',person.password);await p.click('#login-form button');await p.locator('#user-mfa-form').waitFor();assert.equal(await p.locator('.auth-qr').count(),0,'Reentrada não pode recriar autenticador');}
 await finishMfa(p,login);
}else if(await p.locator('#user-mfa-form').count()){await finishMfa(p,login);}
await p.locator('#logout').waitFor();await p.waitForFunction(()=>typeof state!=='undefined'&&state?.records);saved[login].state=await context.storageState();fs.writeFileSync(privateFile,JSON.stringify(saved));return p;}
async function go(p,route){const same=new URL(p.url()).hash==='#'+route;await p.evaluate(()=>{document.querySelector('#main')?.removeAttribute('data-route');});if(same)await p.reload();else await p.goto(base+'/#'+route);await p.waitForFunction(()=>typeof state!=='undefined'&&state?.records);await p.locator('#main h1').first().waitFor();await p.waitForFunction(route=>document.querySelector('#main')?.dataset.route==='#'+route,route);}
async function ready(p,id='record-text'){await p.waitForFunction(id=>typeof tinymce!=='undefined'&&tinymce.get(id)?.initialized,id);}
async function rich(p,html,id='record-text'){await ready(p,id);await p.evaluate(({id,html})=>{const e=tinymce.get(id);e.setContent(html);e.fire('change');},{id,html});}
async function record(p,id){return p.evaluate(id=>state.records.find(r=>r.id===id),id);}
async function edition(p){return p.evaluate(id=>state.editions.find(e=>e.id===id),meta.edition);}
async function saveRecord(p,kind='draft'){await p.click('button[value='+kind+']');await p.waitForURL(/#registro\//);meta.record=new URL(p.url()).hash.split('/')[1];fs.writeFileSync(metaFile,JSON.stringify(meta));}
try{
await step('Ativação e MFA do Operador Maverick',async()=>{page=await account('maverick');assert((await page.locator('.sidebar-bottom').textContent()).includes('Maverick'));assert.equal(await page.locator('[data-nav=revisao]:visible').count(),0);});
if(phase===1){
await step('Validação do envio vazio e assunto com limite de 160 caracteres',async()=>{await go(page,'novo');await ready(page);await page.click('button[value=review]');await page.getByText('Preencha o assunto e conte o que aconteceu antes de enviar.',{exact:true}).waitFor();assert(page.url().endsWith('#novo'));await page.fill('[name=title]','x'.repeat(161));assert.equal((await page.inputValue('[name=title]')).length,160);});
await step('Preencher todos os campos, foto horizontal/vertical e salvar rascunho',async()=>{await page.fill('[name=title]','Maverick: iluminação São João 😀 <img src=x>');await page.selectOption('[name=category]','Manutenção');await page.fill('[name=local]','Garagem & salão <teste>');await page.fill('[name=date]','2024-02-29');await page.fill('[name=who]','Equipe José d’Ávila');await page.selectOption('[name=progress]','Em andamento');await rich(page,'<p><strong>A equipe trocou as lampadas</strong> da garagem. O serviço foi concluido.</p>');
for(const [index,w,h] of [[0,960,640],[1,640,960]]){const png=await page.evaluate(({w,h})=>{const c=document.createElement('canvas');c.width=w;c.height=h;const x=c.getContext('2d');x.fillStyle='#3972a4';x.fillRect(0,0,w,h);x.fillStyle='#fff';x.font='35px sans-serif';x.fillText('FOTO SINTÉTICA QA',20,70);return c.toDataURL('image/png').split(',')[1];},{w,h});await page.setInputFiles('#photos-input',{name:'sintetica-'+index+'.png',mimeType:'image/png',buffer:Buffer.from(png,'base64')});await page.waitForFunction(n=>workingPhotos.length===n&&!document.querySelector('#photos-input').disabled,index+1);}
await page.selectOption('[data-phase="0"]','Antes');await page.selectOption('[data-phase="1"]','Depois');await page.fill('[data-caption="0"]','Antes: teste sintético');await page.fill('[data-caption="1"]','Depois: teste sintético');await saveRecord(page);await page.reload();await page.locator('.detail-text').waitFor();const r=await record(page,meta.record);assert.equal(r.local,'Garagem & salão <teste>');assert.equal(r.date,'2024-02-29');assert.equal(r.who,'Equipe José d’Ávila');assert.equal(r.photos.length,2);assert(r.photos.every(p=>p.src.includes('/api/documents/record/')));assert.equal(await page.locator('.page-head img').count(),0);assert(await page.locator('.photos-detail img').evaluateAll(xs=>xs.every(x=>x.complete&&x.naturalWidth>0)));});
await step('Editor de fotos: cancelar, girar, aplicar e restaurar',async()=>{await go(page,'novo/'+meta.record);await ready(page);const original=await page.evaluate(()=>workingPhotos[0].src);await page.locator('[data-adjust-photo="0"]').click();await page.getByText('Luz e cores',{exact:true}).waitFor();await page.locator('[data-cancel-photo]').click();assert.equal(await page.evaluate(()=>workingPhotos[0].src),original);await page.locator('[data-adjust-photo="0"]').click();await page.getByText('Enquadramento',{exact:true}).click();await page.getByText('Girar',{exact:true}).click();await page.getByText('+90°',{exact:true}).click();await page.getByRole('button',{name:'Aplicar ajustes',exact:true}).click();await page.locator('.photo-editor-dialog').waitFor({state:'detached'});assert(await page.evaluate(()=>workingPhotos[0].height>workingPhotos[0].width));await page.locator('[data-adjust-photo="0"]').click();await page.locator('[data-restore-photo]').click();await page.locator('.photo-editor-dialog').waitFor({state:'detached'});assert(await page.evaluate(()=>workingPhotos[0].width>workingPhotos[0].height));await saveRecord(page);});
await step('Editar e persistir cada categoria e situação do serviço',async()=>{for(const category of ['Obra','Compra','Manutenção','Reparo','Serviço','Evento','Nota solta','Outro']){await go(page,'novo/'+meta.record);await ready(page);await page.selectOption('[name=category]',category);await saveRecord(page);await page.reload();await page.locator('.detail-text').waitFor();assert.equal((await record(page,meta.record)).category,category);}for(const progress of ['Não informado','Em andamento','Concluído']){await go(page,'novo/'+meta.record);await ready(page);await page.selectOption('[name=progress]',progress);await saveRecord(page);assert.equal((await record(page,meta.record)).progress,progress);}});
await step('Revisão real de texto com IA: consentimento e preservação do original',async()=>{await go(page,'novo/'+meta.record);await ready(page);const original=await page.evaluate(()=>tinymce.get('record-text').getContent());await page.getByRole('button',{name:'Revisar com IA',exact:true}).click();await page.locator('.ai-request:enabled').waitFor();await page.locator('.ai-request').click();await page.waitForFunction(()=>{const d=document.querySelector('.ai-review-dialog');return d?.querySelector('.ai-request').hidden||d?.querySelector('.ai-request:not(:disabled)');},{},{timeout:45000});const text=await page.locator('.ai-status').textContent();assert(/sugestão|não sugeriu/.test(text),text);assert.equal(await page.evaluate(()=>tinymce.get('record-text').getContent()),original);await page.locator('.ai-cancel').click();await page.getByRole('button',{name:'Revisar com IA',exact:true}).click();await page.locator('.ai-cancel').click();await saveRecord(page);});
await step('Rascunho local: recarregar, recuperar e salvar alterações',async()=>{await go(page,'novo/'+meta.record);await ready(page);await page.fill('[name=local]','Maverick: rascunho recuperado');await page.waitForTimeout(500);await page.reload();await ready(page);await page.waitForFunction(()=>document.querySelector('[name=local]')?.value==='Maverick: rascunho recuperado');await saveRecord(page);assert.equal((await record(page,meta.record)).local,'Maverick: rascunho recuperado');});
await step('Privacidade: outro Operador não vê rascunho de Maverick',async()=>{const other=await account('iceman');assert(!await record(other,meta.record));await other.close();});
await step('Enviar para revisão, bloquear edição e comandos administrativos',async()=>{await go(page,'novo/'+meta.record);await ready(page);await page.click('button[value=review]');await page.waitForURL(/#registro\//);assert.equal((await record(page,meta.record)).status,'review');assert.equal(await page.locator('#approve-record,#trash-record,#request-fix').count(),0);assert.equal(await page.locator('a[href="#novo/'+meta.record+'"]').count(),0,'Não deve oferecer edição de registro já enviado');});
await step('Administrador pede complemento; Maverick corrige e reenvia',async()=>{const admin=await account('viper');await go(admin,'registro/'+meta.record);await admin.click('#request-fix');await ready(admin,'feedback');await rich(admin,'<p>Informe o bloco e a equipe que realizou o serviço.</p>','feedback');await admin.click('#save-feedback');await admin.waitForURL(/#registro\//);await page.reload();await page.locator('.detail-text').waitFor();assert.equal((await record(page,meta.record)).status,'fix');await page.locator('a[href="#novo/'+meta.record+'"]').click();await ready(page);await page.fill('[name=local]','Bloco A — confirmado por Maverick');await page.click('button[value=review]');await page.waitForURL(/#registro\//);await go(admin,'registro/'+meta.record);await admin.locator('#approve-record').waitFor();await admin.click('#approve-record');await admin.waitForFunction(id=>state.records.find(r=>r.id===id)?.status==='ready',meta.record);await page.reload();await page.locator('.detail-text').waitFor();assert.equal((await record(page,meta.record)).status,'ready');assert.equal(await page.locator('a[href="#novo/'+meta.record+'"]').count(),0);assert.equal(await admin.locator('#approve-record,#request-fix').count(),0,'Não deve oferecer revisão repetida de registro conferido');await admin.close();});
await step('Busca, filtros e tela mobile do registro',async()=>{await go(page,'registros');await page.fill('#search','Maverick');await page.selectOption('#filter-status','ready');assert(await page.locator('#record-grid').textContent());await page.setViewportSize({width:390,height:844});await go(page,'registro/'+meta.record);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:path.join(out,'registro-mobile.png'),fullPage:true});await page.setViewportSize({width:1365,height:950});});
}
if(phase===2){
await step('Criar informe com título/período e adicionar registro conferido',async()=>{await go(page,'informes');await page.click('#new-edition');await page.fill('#edition-title','Informe Maverick — teste sintético');await page.fill('#edition-period','Outubro de 2026');await page.click('#create-edition');await page.waitForURL(/#editor\//);meta.edition=new URL(page.url()).hash.split('/')[1];fs.writeFileSync(metaFile,JSON.stringify(meta));await go(page,'selecionar/'+meta.edition);await page.check('#select-'+meta.record);await page.click('#add-separate');await page.waitForURL(/#editor\//);await ready(page,'rich-editor');assert((await edition(page)).blocks[0].sources.some(s=>s.id===meta.record));});
await step('Todos os modelos de bloco e bloco personalizado, com conteúdo persistido',async()=>{for(const type of ['Palavra do Síndico','Informações gerais','Atenção especial','Regras dos espaços','Convivência','Grade esportiva','Contatos','Matéria']){await page.click('#add-block');await page.locator('[data-type="'+type+'"]').click();await ready(page,'rich-editor');await page.fill('#block-title','Maverick · '+type);await rich(page,type==='Grade esportiva'?'<table><tbody><tr><td>Futebol</td><td>Segunda</td><td>19h</td><td>Quadra</td></tr></tbody></table>':'<p>Conteúdo sintético para '+type+'.</p>','rich-editor');await page.click('#save-editor');await ready(page,'rich-editor');}await page.click('#add-block');await page.fill('#custom-block-name','Achados e perdidos QA');await page.locator('#custom-block-form button').click();await ready(page,'rich-editor');await rich(page,'<p>Uma chave sintética foi encontrada.</p>','rich-editor');await page.click('#save-editor');await page.reload();await ready(page,'rich-editor');assert.equal((await edition(page)).blocks.length,10);assert((await edition(page)).blocks.some(b=>b.type==='Achados e perdidos QA'));});
await step('Duplicar, reordenar, excluir e desfazer bloco completo',async()=>{await page.click('#duplicate-block');await ready(page,'rich-editor');assert.equal((await edition(page)).blocks.length,11);await page.click('#move-up');await ready(page,'rich-editor');await page.click('#move-down');await ready(page,'rich-editor');await page.click('#delete-block');await ready(page,'rich-editor');assert.equal((await edition(page)).blocks.length,10);await page.click('#undo-block');await ready(page,'rich-editor');assert.equal((await edition(page)).blocks.length,11);});
await step('Fotos do informe: legenda, formato, destaque, capa e ocultar/mostrar',async()=>{await page.locator('[data-block="0"]').click();await ready(page,'rich-editor');await page.fill('[data-edit-caption="0"]','Legenda editorial de Maverick');await page.selectOption('[data-orientation="0"]','portrait');await ready(page,'rich-editor');await page.locator('[data-feature-photo="0"]').click();await ready(page,'rich-editor');await page.locator('[data-cover="0"]').click();await page.waitForTimeout(300);await page.locator('[data-hide="0"]').click();await ready(page,'rich-editor');assert((await edition(page)).blocks[0].photos[0].hidden);await page.locator('[data-hide="0"]').click();await ready(page,'rich-editor');await page.click('#save-editor');await page.reload();await ready(page,'rich-editor');const e=await edition(page);assert.equal(e.blocks[0].photos[0].caption,'Legenda editorial de Maverick');assert(e.blocks[0].photos[0].featured);assert.equal(e.blocks[0].photos[0].orientation,'portrait');assert(!e.blocks[0].photos[0].hidden);});
await step('Prévia desktop/mobile e exportação de rascunho marcado',async()=>{await page.click('#go-preview');await page.waitForURL(/#previa\//);await page.click('#toggle-width');assert(await page.locator('.publication').evaluate(e=>e.classList.contains('mobile-preview')));const download=page.waitForEvent('download');await page.getByRole('link',{name:'Baixar rascunho marcado'}).click();const d=await download;const stream=await d.createReadStream();let html='';for await(const chunk of stream)html+=chunk.toString();assert(html.includes('RASCUNHO'));assert(html.includes('Informe Maverick'));await page.screenshot({path:path.join(out,'previa-informe.png'),fullPage:true});});
await step('Enviar à aprovação e impedir Operador de aprovar/publicar ou editar revisão pendente',async()=>{await page.click('#submit-approval');await page.locator('#submit-approval').waitFor({state:'detached'});assert.equal(await page.locator('#approve-edition,#publish-edition').count(),0);assert((await edition(page))._pendingRevisionId);meta.revision=(await edition(page))._pendingRevisionId;fs.writeFileSync(metaFile,JSON.stringify(meta));await go(page,'editor/'+meta.edition);assert.equal(await page.locator('#save-editor:enabled').count(),0,'Revisão pendente deve abrir somente para leitura');});
}
if(phase===3){
const admin=await account('viper');
await step('Administrador devolve informe; Maverick ajusta e reenvia',async()=>{await go(admin,'previa/'+meta.edition);if(await admin.locator('#return-edition').count()){admin.once('dialog',d=>d.accept('Corrigir a informação sintética do bloco principal.'));await admin.click('#return-edition');await admin.waitForURL(/#editor\//);}else{assert.equal((await edition(admin))._workflowState,'returned');}await go(page,'editor/'+meta.edition);await ready(page,'rich-editor');await page.fill('#block-title','Maverick: título ajustado após devolução');await page.click('#save-editor');await ready(page,'rich-editor');await page.click('#go-preview');await page.waitForURL(/#previa\//);await page.click('#submit-approval');await page.locator('#submit-approval').waitFor({state:'detached'});meta.revision=(await edition(page))._pendingRevisionId;fs.writeFileSync(metaFile,JSON.stringify(meta));});
await step('Administrador aprova revisão exata e gera publicação oficial',async()=>{await admin.reload();await go(admin,'previa/'+meta.edition);admin.once('dialog',d=>d.accept());await admin.click('#approve-edition');await admin.locator('#publish-edition').waitFor();admin.once('dialog',d=>d.accept());await admin.click('#publish-edition');await admin.waitForURL(/#publicado\//);meta.publication=new URL(admin.url()).hash.split('/')[1];fs.writeFileSync(metaFile,JSON.stringify(meta));});
await step('Maverick lê e baixa HTML oficial com todas as fotos e conteúdo',async()=>{await go(page,'publicado/'+meta.publication);const download=page.waitForEvent('download');await page.click('#download');const d=await download,stream=await d.createReadStream();let html='';for await(const chunk of stream)html+=chunk.toString();assert(html.includes('Informe Maverick'));assert(html.includes('data:image/'));assert(html.includes('Legenda editorial de Maverick'));assert(!html.includes('RASCUNHO'));const api=await page.request.get(base+'/api/publications/'+meta.publication+'/artifact');assert.equal(api.status(),200);assert.equal(await api.text(),html);});
await step('Administrador arquiva/restaura fonte sem alterar publicação',async()=>{const before=await (await page.request.get(base+'/api/publications/'+meta.publication+'/artifact')).body();await go(admin,'registro/'+meta.record);await admin.click('#trash-record');await admin.click('#confirm-trash');await admin.waitForURL(/#registros$/);await go(admin,'lixeira');await admin.locator('[data-restore-record="'+meta.record+'"]').click();await admin.waitForURL(/#registro\//);const after=await (await page.request.get(base+'/api/publications/'+meta.publication+'/artifact')).body();assert.deepEqual(before,after);});
await step('Operador bloqueado no painel do dono e na emissão de convites',async()=>{const p=await page.request.get(base+'/api/owner/overview');assert.equal(p.status(),403);const q=await page.evaluate(async()=>{try{await authRequest('/api/auth/invitations',{method:'POST',body:JSON.stringify({login:'unauthorized',displayName:'Not allowed',roles:['administrador'],condominiumId:'sqa'})});return 200;}catch(e){return e.status;}});assert.equal(q,403);});
await admin.close();
}
if(phase===4){
await step('Nota solta, campos opcionais vazios e rejeição de arquivo inválido',async()=>{await go(page,'nota');await ready(page);await page.fill('[name=title]','Nota Maverick — segurança do rascunho');await rich(page,'<p>Nota sintética sem detalhes opcionais.</p>');await page.setInputFiles('#photos-input',{name:'invalido.html',mimeType:'text/html',buffer:Buffer.from('<html>invalid</html>')});await page.waitForFunction(()=>!document.querySelector('#photos-input').disabled);assert.equal(await page.evaluate(()=>workingPhotos.length),0);await page.click('button[value=draft]');await page.waitForURL(/#registro\//);meta.note=new URL(page.url()).hash.split('/')[1];fs.writeFileSync(metaFile,JSON.stringify(meta));const r=await record(page,meta.note);assert.equal(r.category,'Nota solta');assert.equal(r.local,'');assert.equal(r.date,'');assert.equal(r.photos.length,0);});
await step('Navegação protege alterações: continuar, descartar e salvar antes de sair',async()=>{await go(page,'novo/'+meta.note);await ready(page);await page.fill('[name=local]','Alteração a descartar');await page.locator('[data-nav=inicio]').click();await page.locator('#draft-stay').click();assert(page.url().endsWith('#novo/'+meta.note));assert.equal(await page.inputValue('[name=local]'),'Alteração a descartar');await page.locator('[data-nav=inicio]').click();await page.locator('#draft-discard').click();await page.waitForURL(/#inicio$/);await go(page,'novo/'+meta.note);await ready(page);assert.equal(await page.inputValue('[name=local]'),'');await page.fill('[name=local]','Salvo antes de sair');await page.locator('[data-nav=inicio]').click();await page.locator('#draft-save').click();await page.waitForURL(/#inicio$/);await go(page,'registro/'+meta.note);await page.locator('.detail-text').waitFor();assert.equal((await record(page,meta.note)).local,'Salvo antes de sair');});
await step('Falha real de conexão: rascunho baixável e repetição sem perda',async()=>{await go(page,'novo/'+meta.note);await ready(page);await page.fill('[name=local]','Trabalho salvo após reconectar');await page.context().setOffline(true);await page.click('button[value=draft]');await page.locator('#storage-recovery').waitFor();assert(await page.evaluate(()=>storageBlocked));const downloading=page.waitForEvent('download');await page.click('#download-draft');const download=await downloading,stream=await download.createReadStream();let json='';for await(const chunk of stream)json+=chunk.toString();assert.equal(JSON.parse(json).fields.local,'Trabalho salvo após reconectar');await page.context().setOffline(false);await page.click('#retry-draft');await page.locator('#storage-recovery').waitFor({state:'detached'});await page.waitForFunction(()=>!storageBlocked&&!saveBusyCount&&!activeDraft?.dirty);await page.reload();await ready(page);assert.equal(await page.inputValue('[name=local]'),'Trabalho salvo após reconectar');});
await step('Duas abas: conflito 409 preserva servidor e permite baixar alteração local',async()=>{await go(page,'novo/'+meta.note);await ready(page);const tab=await page.context().newPage();tab.setDefaultTimeout(12000);await go(tab,'novo/'+meta.note);await ready(tab);await tab.fill('[name=local]','Alteração vencedora da segunda aba');await tab.click('button[value=draft]');await tab.waitForURL(/#registro\//);await page.fill('[name=local]','Alteração concorrente preservada localmente');await page.click('button[value=draft]');await page.locator('#storage-recovery').waitFor();assert.equal(await page.locator('#retry-draft').count(),0);const downloading=page.waitForEvent('download');await page.click('#download-draft');const download=await downloading,stream=await download.createReadStream();let json='';for await(const chunk of stream)json+=chunk.toString();assert.equal(JSON.parse(json).fields.local,'Alteração concorrente preservada localmente');const workspace=await (await page.request.get(base+'/api/workspace')).json();assert.equal(workspace.state.records.find(r=>r.id===meta.note).local,'Alteração vencedora da segunda aba');await page.click('#reload-state');await ready(page);assert.equal(await page.inputValue('[name=local]'),'Alteração concorrente preservada localmente','Cópia local precisa sobreviver à recarga');await page.locator('[data-nav=inicio]').click();await page.locator('#draft-discard').click();await page.waitForURL(/#inicio$/);await go(page,'registro/'+meta.note);assert.equal((await record(page,meta.note)).local,'Alteração vencedora da segunda aba');await tab.close();});
await step('Telemetria reconhece registro conferido e recusa rascunho privado de outro Operador',async()=>{const admin=await account('viper');const ok=await admin.evaluate(id=>authRequest('/api/diagnostics/client',{method:'POST',body:JSON.stringify({kind:'document_view',page:'registro',resourceType:'record',resourceId:id})}),meta.record);assert.equal(ok.status,'received');await admin.close();const other=await account('iceman');const denied=await other.evaluate(async id=>{try{await authRequest('/api/diagnostics/client',{method:'POST',body:JSON.stringify({kind:'document_view',page:'registro',resourceType:'record',resourceId:id})});return 200;}catch(e){return e.status;}},meta.note);assert.equal(denied,404);await other.close();});
await step('Logout, recuperação sem revelar existência da conta e reentrada com MFA',async()=>{await page.click('#logout');await page.locator('#login-form').waitFor();const results=[];for(const login of ['maverick','usuario-inexistente-qa']){await page.locator('summary').click();await page.fill('#recovery-form [name=login]',login);const response=page.waitForResponse(r=>r.url().endsWith('/api/auth/recovery/request'));await page.click('#recovery-form button');const r=await response;assert.equal(r.status(),202);results.push(await r.json());await page.locator('#login-form').waitFor();}assert.deepEqual(results[0],results[1]);const person=people.find(p=>p.login==='maverick');await page.fill('#login-form [name=login]','maverick');await page.fill('#login-form [name=password]',person.password);await page.click('#login-form button');await page.locator('#user-mfa-form').waitFor();assert.equal(await page.locator('.auth-qr').count(),0,'Conta já cadastrada não deve exibir novo QR');const protectedWorkspace=await page.request.get(base+'/api/workspace');assert.equal(protectedWorkspace.status(),401,'Senha sem MFA não estabelece sessão autorizada');await finishMfa(page,'maverick');await page.waitForFunction(()=>state?.records);});
}
await step('Nenhuma exceção JavaScript na jornada',async()=>assert.deepEqual(jsErrors,[]));
}catch(e){console.error('FAIL '+current+': '+redact(e.message));process.exitCode=1;if(page&&await page.locator('#login-form,#activate-form,#user-mfa-form,.auth-qr').count()===0)await page.screenshot({path:path.join(out,'phase-'+phase+'-failure.png'),fullPage:true}).catch(()=>{});
}finally{for(const [login,c] of Object.entries(contexts)){saved[login]??={};saved[login].state=await c.storageState();}fs.writeFileSync(privateFile,JSON.stringify(saved));fs.writeFileSync(metaFile,JSON.stringify(meta));fs.writeFileSync(path.join(out,'phase-'+phase+'-'+Date.now()+'.json'),JSON.stringify({phase,checks,jsErrors,httpErrors},null,2));await browser.close();}})();
